# Site settings
title: Kimfucious Bootstrap Jekyll
email: example@example.com 
brand: Site Brand
baseurl: ""
author: Kimfucious
description: A clean Jekyll theme with baked in Bootstrap 4
url:

# Build settings
permalink: :title/

# Not using because Gulp is now processing SCSS
# sass:
#   sass_dir: css
#   style: compressed

# Collections
collections:
  my_collection:
    output: true
    # permalink: /:collection/:name

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post 
  - scope:
      path: ""
      type: pages
    values:
      layout: default 
  - scope:
      path: ""
      type: my_collection
    values:
      layout: collection-item

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/page:num"
  sort_reverse: true

# Picturefill presets
picture:
  source: "assets/images/optimized_originals"
  output: "assets/images/generated"
  markup: "picture"
  presets:
    post_image:
      attr:
        class: "image--post-image"
        itemprop: "image"
      ppi: [1,2]
      source_1120:
        media: "(min-width: 400px)"
        width: "737"
      source_default:
        width: "400"

# Plugins
plugins: [jekyll-paginate-v2, jemoji]

# Social icons
show_social_icons: true
github_username: 
twitter_username: 
linkedin_username: 
facebook_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM