# Site settings
title: Site Title
email: example@example.com 
brand: Site Brand
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Collections
collections:
  my_collection:
    output: true

# Plugins
plugins: [jekyll-paginate]
paginate: 4 
paginate_path: "/page:num"

# Social icons
show_social_icons: true
github_username: 
twitter_username: 
linkedin_username: 
facebook_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true