# Site settings
title: Kimfucious Bootstrap Jekyll
email: example@example.com 
brand: Site Brand
author: Kimfucious
description: A clean Jekyll theme with baked in Bootstrap 4
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: compressed

# Collections
collections:
  my_collection:
    output: true
    # permalink: /:collection/:name

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post 
  - scope:
      path: ""
      type: pages
    values:
      layout: default 
  - scope:
      path: ""
      type: my_collection
    values:
      layout: collection-item

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "kimfucious.gemspec",
  "node_modules",
  "package.json",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/page:num"
  sort_reverse: true

# Plugins
plugins: [jekyll-paginate-v2, jemoji]

# Social icons
show_social_icons: true
github_username: 
twitter_username: 
linkedin_username: 
facebook_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
highlighter: none
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true