# Site settings
author: Kimfucious
baseurl: ""
brand: Sakura
copyright: abts.io
description: A clean Jekyll theme with baked in Bootstrap 4, responsive images, and more...
email: example@example.com 
title: Sakura Jekyll Theme 
url:

# Build settings
permalink: :title/

# Not using because Gulp is now processing SCSS
# sass:
#   sass_dir: css
#   style: compressed

# Collections
collections:
  docs:
    output: true
    # permalink: /:collection/:title

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post 
  - scope:
      path: ""
      type: pages
    values:
      layout: default 
  - scope:
      path: ""
      type: docs
    values:
      layout: collection-item

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "yarn-error.log",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/page:num"
  sort_reverse: true

# Plugins
plugins: [jekyll-paginate-v2, jemoji]

# Social icons
show_social_icons: true
github_username: 
twitter_username: 
linkedin_username: 
facebook_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM