# Site settings
title: Site Title
email: example@example.com 
brand: Site Brand
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: compressed

# Collections
collections:
  my_collection:
    output: true

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "kimfucious.gemspec",
  "node_modules",
  "package.json",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/page:num"
  sort_reverse: true

# Plugins
plugins: [jekyll-paginate-v2]

# Social icons
show_social_icons: true
github_username: 
twitter_username: 
linkedin_username: 
facebook_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
highlighter: none
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true